services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ecommerce_rabbitmq_prod
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-secret123}
    volumes:
      - rabbitmq_prod_data:/var/lib/rabbitmq
    restart: always

volumes:
  rabbitmq_prod_data: