/**
 * 🔧 One-time Migration Script: Convert legacy full image URLs → S3 keys in DB
 *
 * WHY: Before Task 4.4 (Round 11), the system stored full URLs in `imageUrl`.
 *      If CloudFront domain or S3 bucket ever changes, those old URLs will break.
 *      This script converts all legacy records to use the clean key format
 *      (e.g. "products/abc.webp") so resolveImageUrl() can resolve them dynamically.
 *
 * SAFE TO RUN: Dry-run mode by default. Pass --execute to apply changes.
 *
 * Usage:
 *   Dry run (preview):  npx dotenv-cli -e .env.production -- npx ts-node scripts/migrate-image-url-to-key.ts
 *   Execute:            npx dotenv-cli -e .env.production -- npx ts-node scripts/migrate-image-url-to-key.ts --execute
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const DRY_RUN = !process.argv.includes('--execute');

// All possible URL prefixes that were generated by the OLD upload.service.ts.
// The script will strip whichever prefix matches, leaving a clean key.
const BUCKET_NAME = process.env.AWS_BUCKET_NAME ?? 'ecommerce-products';
const REGION = process.env.AWS_REGION ?? 'ap-southeast-1';

const KNOWN_PREFIXES = [
  // CloudFront (most likely for production)
  process.env.CLOUDFRONT_URL ? `${process.env.CLOUDFRONT_URL}/` : null,
  // MinIO / custom endpoint (local dev)
  process.env.AWS_ENDPOINT ? `${process.env.AWS_ENDPOINT}/${BUCKET_NAME}/` : null,
  // Direct S3
  `https://${BUCKET_NAME}.s3.${REGION}.amazonaws.com/`,
  // Path-style S3 (older format)
  `https://s3.${REGION}.amazonaws.com/${BUCKET_NAME}/`,
].filter(Boolean) as string[];

function extractKey(fullUrl: string): string | null {
  for (const prefix of KNOWN_PREFIXES) {
    if (fullUrl.startsWith(prefix)) {
      return fullUrl.slice(prefix.length);
    }
  }
  return null;
}

async function migrate() {
  console.log(`\n🔍 Mode: ${DRY_RUN ? '**DRY RUN** (no changes)' : '**EXECUTE** (writing to DB)'}`);
  console.log(`📦 Bucket: ${BUCKET_NAME} | Region: ${REGION}`);
  console.log(`🔗 Known prefixes to strip:`);
  KNOWN_PREFIXES.forEach(p => console.log(`   - ${p}`));
  console.log('');

  // Find ALL products with legacy full URL (starts with http)
  const legacy = await prisma.product.findMany({
    where: { imageUrl: { startsWith: 'http' } },
    select: { id: true, imageUrl: true },
  });

  if (legacy.length === 0) {
    console.log('✅ No legacy records found. DB is already clean!');
    await prisma.$disconnect();
    return;
  }

  console.log(`Found ${legacy.length} product(s) with legacy full URL.\n`);

  let converted = 0;
  let skipped = 0;

  for (const p of legacy) {
    if (!p.imageUrl) continue;

    const key = extractKey(p.imageUrl);

    if (!key) {
      console.warn(`  ⚠️  #${p.id}: Cannot match prefix — SKIPPING`);
      console.warn(`       URL: ${p.imageUrl}`);
      skipped++;
      continue;
    }

    console.log(`  ✅ #${p.id}: ${p.imageUrl}`);
    console.log(`        → ${key}`);

    if (!DRY_RUN) {
      await prisma.product.update({
        where: { id: p.id },
        data: { imageUrl: key },
      });
    }

    converted++;
  }

  console.log(`\n📊 Summary:`);
  console.log(`   Converted: ${converted}`);
  console.log(`   Skipped (unknown prefix): ${skipped}`);

  if (DRY_RUN) {
    console.log(`\n⚠️  DRY RUN — no changes written.`);
    console.log(`   To apply, run with --execute flag:`);
    console.log(`   npx dotenv-cli -e .env.production -- npx ts-node scripts/migrate-image-url-to-key.ts --execute`);
  } else {
    console.log(`\n🎉 Migration complete! All product image URLs are now clean S3 keys.`);
  }

  await prisma.$disconnect();
}

migrate().catch(async (err) => {
  console.error('Migration failed:', err);
  await prisma.$disconnect();
  process.exit(1);
});
