name: Deploy Angular to AWS S3 & CloudFront

# 1. KHI NÀO THÌ CHẠY?
# Kịch bản này sẽ tự động kích hoạt khi có code mới push lên nhánh "main"
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # GitHub sẽ mượn 1 máy ảo Ubuntu để chạy

    steps:
      - name: 📥 Kéo code về máy ảo
        uses: actions/checkout@v4

      - name: ⚙️ Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Cài đặt thư viện (npm install)
        run: npm ci

      - name: 🛠️ Build code Angular ra HTML/CSS/JS
        run: npm run build -- --configuration production

      - name: 🔑 Đăng nhập vào AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 🚀 Đẩy code lên S3 Bucket
        run: aws s3 sync dist/frontend/browser s3://${{ secrets.S3_FRONTEND_BUCKET }} --delete

      - name: 🧹 Xóa bộ nhớ đệm CloudFront (Invalidation)
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --paths "/*"